### ISSUE TITLE
[Stage0] チュートリアル終了後の仕様

### ISSUE THREAD

**Issue by NeecMakotoTakanashi** [NeecMakotoTakanashi/Neec_ProjectTamagoyaki#12]
現在はチュートリアル終了（エネミー３体撃破）時に本線へジャンプしてしまうが仕様あれば連絡

**Comment by NeecShigekazuIto** [comment]
本線に入ったとき、正面が道になるようにしました。
フェードインアウト入れた方がいい気もしますが、必要であればまたissue立ててください。
